-- Reset "Store Id" identity column to start from 1 and fix gaps
-- Run this in Supabase SQL Editor
-- This will renumber all existing stores sequentially (1, 2, 3...) and reset the sequence

-- Step 1: Temporarily change identity column to allow manual updates
-- (Skip this if column is already GENERATED BY DEFAULT)
DO $$
BEGIN
    -- Check if column is GENERATED ALWAYS and change to GENERATED BY DEFAULT temporarily
    IF EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_name = 'stores' 
        AND column_name = 'Store Id'
        AND is_identity = 'YES'
    ) THEN
        -- Change to GENERATED BY DEFAULT to allow manual updates
        ALTER TABLE stores 
        ALTER COLUMN "Store Id" SET GENERATED BY DEFAULT;
        
        RAISE NOTICE 'Changed identity column to GENERATED BY DEFAULT for updates';
    END IF;
END $$;

-- Step 2: Update all existing rows to be sequential starting from 1
-- This fixes the gap issue (10-21, then 164-168 will become 1, 2, 3, etc.)
WITH ranked_stores AS (
  SELECT 
    ctid,  -- Use ctid as unique identifier (PostgreSQL internal row identifier)
    ROW_NUMBER() OVER (
      ORDER BY 
        -- Order by current Store Id if it's numeric and reasonable
        CASE 
          WHEN "Store Id" IS NOT NULL AND "Store Id"::text ~ '^[0-9]+$' 
          THEN ("Store Id")::INTEGER
          ELSE 999999999
        END,
        -- Then by Created Date (NULLS LAST handles nulls)
        "Created Date" ASC NULLS LAST,
        -- Finally by Store Name for consistent ordering
        COALESCE("Store Name", '') ASC
    ) as new_store_id
  FROM stores
)
UPDATE stores
SET "Store Id" = ranked_stores.new_store_id
FROM ranked_stores
WHERE stores.ctid = ranked_stores.ctid;

-- Step 3: Find the maximum Store Id and reset sequence to continue from there
DO $$
DECLARE
    max_id INTEGER;
    seq_name TEXT;
BEGIN
    -- Get the maximum Store Id
    SELECT COALESCE(MAX("Store Id"), 0) INTO max_id FROM stores;
    
    -- Find the sequence name for Store Id
    SELECT pg_get_serial_sequence('stores', 'Store Id') INTO seq_name;
    
    IF seq_name IS NOT NULL THEN
        -- Reset sequence to start from max_id + 1
        EXECUTE format('SELECT setval(%L, %s, false)', seq_name, max_id);
        RAISE NOTICE 'Reset sequence % to start from %', seq_name, max_id + 1;
    ELSE
        -- If no sequence found, try to restart the identity using dynamic SQL
        EXECUTE format('ALTER TABLE stores ALTER COLUMN "Store Id" RESTART WITH %s', max_id + 1);
        RAISE NOTICE 'Reset identity column to start from %', max_id + 1;
    END IF;
END $$;

-- Step 4: Change back to GENERATED ALWAYS (if you want strict identity)
-- Uncomment the line below if you want to prevent manual updates
-- ALTER TABLE stores ALTER COLUMN "Store Id" SET GENERATED ALWAYS;

-- Step 5: Verify the results
SELECT 
  "Store Id",
  "Store Name",
  "Created Date"
FROM stores
ORDER BY "Store Id"
LIMIT 20;

-- Show total count and max ID
SELECT 
    COUNT(*) as total_stores,
    MAX("Store Id") as max_store_id,
    MIN("Store Id") as min_store_id
FROM stores;

-- Verify sequence value
SELECT 
    schemaname,
    sequencename,
    last_value,
    start_value
FROM pg_sequences
WHERE sequencename LIKE '%store_id%' OR sequencename LIKE '%Store_Id%';

